Add validate-pyproject dependency and include additional files in wheel package

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -86,7 +86,6 @@ jobs:
           PACKAGE_VERSION=$(echo "$WHEEL_FILE" | sed -n "s/.*${PACKAGE_NAME}-\(.*\)-py3-none-any\.whl/\1/p")
 
           mv "$WHEEL_FILE" release/
-          mv config.json release/
           mv static release/
           chmod +x release/install_cyber_query_ai.sh
           mv release ${PACKAGE_NAME}_${PACKAGE_VERSION}
@@ -175,8 +174,18 @@ jobs:
             exit 1
           fi
 
-          if [ ! -f "README.txt" ]; then
+          if [ ! -f "README.md" ]; then
             echo "README file not found"
+            exit 1
+          fi
+
+          if [ ! -f "SECURITY.md" ]; then
+            echo "SECURITY file not found"
+            exit 1
+          fi
+
+          if [ ! -f "LICENSE" ]; then
+            echo "LICENSE file not found"
             exit 1
           fi
 
